### ISSUE TITLE
Tengo un problema.

### ISSUE THREAD

**Issue by iwzst** [MrRojito-Dev/RojiBot#1]
Mire, cuando intento prender el proyecto me sale siguiente mensaje en la consola:
`DiscordAPIError: [TOKEN_INVALID]`
tiene alguna de idea de como solucionarlo?

**Comment by MrRojito-Dev** [comment]
Debes crear un archivo llamado `.env` en la carpeta principal del bot (en donde está el package.json y todo eso).
Dentro del archivo `.env` debes poner lo siguiente: `DISCORD_TOKEN="Token de un bot"`. Puedes poner el token de algún bot de pruebas para verificar que todo funcione, si es que funciona, en la consola logeará el nombre del bot.

Eso sí, cuando hagas una pull request, **recuerda no subir ese archivo**...
